FB_PAGE_TOKEN = "EAAbHPY5s4I4BO4lcMP4spMukwjZCmNdt0twbIGVdHAqUY6Q4OYThmtoFbOqx2tCw3yyZB8fKEnbxQbIAiNc7hvvzO4mVZBLnCpIOHvjaRRvpx9DbQjSUSWtPexZC1j812CZCu5DF6OFZB1sHmVSivK8cb9TvxGFmlJMgQKsF0zAsS0zdNZCbenZCaOZBnt2hZCw5zF0HrK"
FB_PAGE_ID = "2076435142631541"
OPENROUTER_API_KEY = "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"