FB_PAGE_TOKEN = "EAAbHPY5s4I4BO4lcMP4spMukwjZCmNdt0twbIGVdHAqUY6Q4OYThmtoFbOqx2tCw3yyZB8fKEnbxQbIAiNc7hvvzO4mVZBLnCpIOHvjaRRvpx9DbQjSUSWtPexZC1j812CZCu5DF6OFZB1sHmVSivK8cb9TvxGFmlJMgQKsF0zAsS0zdNZCbenZCaOZBnt2hZCw5zF0HrK"
FB_PAGE_ID = "2076435142631541"
OPENROUTER_API_KEY = "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"
IG_TOKEN = "EAAbHPY5s4I4BO6n6qPLdxZByl1sStZBB8v6Ey6LC6I7q9azF20qbzQJMCfjlOBFIuS0PUwhFGsBjU0j2Fj81VtZA8fEZB2s9Uv1tMZCHP8i32kBXM407P7ZAiceDqGSAxbltWACQFfkRAUDfHtAvNsoz2LuhdEShZChehqJZBRFxboNzaoQYEx3zx6dAL9ob"
IG_ID = "17841475106267575"
CLOUDINARY_CLOUD_NAME = "dmva9wprt"
CLOUDINARY_API_KEY = "911835649691683"
CLOUDINARY_API_SECRET = "yQXXul-QP0-5qNCtTiKZWlG_5fk"

[gdrive_service_account]
type = "service_account"
project_id = "xuongbinhgom"
private_key_id = "af25d21e598a8f09c6855fbf18d06570a2968367"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDYu0Lg9E0rxFiE
9BMRF3DsHlrqrtXdFi6/1GzheT5cemaIJ1QF2613B/4hiUiXiz5C51cHnwoypO2I
95VUZsAbe/330UrbXuXHQc+3o9J7l7O/+bTSLudMXy5GiQ8TCjNPWNc0mvDkOjJs
PhkZAmRYkpgyYRwCo0KHjL0Yp0k+5gviMkfSG8WSQqRUzSJRjgC0w7nVFbkWFfOI
as5jyYrHG2FJfKNgwVp87AXTLAyVcKHXnEfTijzwKxR9176ALI3HNAioSKQMWDHX
vygard+yCbYmOGLv/vkT1DeGBEGlU151y0AyzMy69G/s0S1xIN6AkTYc7Ig3QvvV
ouSf3AvXAgMBAAECggEARFHLhEQeq4RKbybNd97Ozu/GsyIH8piShg/9fpoMqXRA
K/1RxEL6jIItfv7arkLLjqWETre4rDxHUJzTKvb06fUNGviTw1FH16cMRpRSvnkU
xZh+gp8cdHuwh7We1d6qTAHyXPfWpeseh/aPTM3vOeiEJ6VrAf3a9AXOeh4JvdSM
AmMrnbPinfnGxK+Z0ytgv8VqJbfKka6FH+6CmmXHpX1Sm3+6kiqMnMZYiIAbcAeV
6ni5X0Kdn+kK1u1B05GEsID03+IM74KYTNtPcWStxLXQ6Hd1Tg3P24XAFBkmGTu/
e0m3RFXkaY9UK4g4F3mIzcvsSwdG5GE9a1B1YbAkYQKBgQD4yXMjtKk1pzCT2S6b
4e0GCFoSITyZFKuAw/tXdmWuC+KDpIuX7pWPUN9ZROtgbzVue47E/F290MdQuc2c
9MirObArVdoksZWq7mz8lal+kB7QOB5jiG5RKGREC30zPjOkr+HnA/mK73PRoznq
1OYPeTAYvKOK63+1hwdSQxUJsQKBgQDfA+Oicy3u2ky61pHXlGek0m2rxxsIaxQk
fuwq/f1+cImru5bk7xPuE1Dyzlv8CXHvdvwA6e9bfW80kVgNlWkpH4sPNoOaT9k+
Sl162tpVGGfpCXILIhVY5/XJTJa3iEYLWN/i+lgsZrlWo/I+ouatlFzwCRcQdS/E
MyYzjT9IBwKBgCwM30ovLtbFJ6DGD66iLimnSOt03xnrwwIlsVcnK5HJoO3WMLFS
GUEq/KD9xv9oMXnCfuD6Hk8BrIjqnTFxViabLEpABUQB/ZIqbTm79irmsc4EYb0V
5xKPqFE0B5MPLG24hrM0zPaAt20jDZo64BFVT+LRY9OxJwepRO6X2h3BAoGAYUyA
F1MrOieSDH4rGSRNZ9LLOIPg3nZhTl71yPgRjgWpevyYI//O8TMKQTUZWsgAJpsB
7aAi5wa96vByu1JxlBiIAjYlisDFpnCpgj1TvoasZzbQw9y19ZkWWiIJK7/P14mJ
/Kx+pbiXqh5TRVKrVBYDylIc9vg5w98RDrLUZicCgYBGmzkO12Oktn+ECbFtrXg2
kYVU430nnERJBjrbnVE2AU+IvhfQeQW3xycvadNxK9gMpQg9Ay9KmDT2AxeLi7o7
odt5p8YlisXWaoYXUjc+hPGPfe0NzJzbyYe4azl9NtTU7Gn4qJ5NUKNzDCtkRTaC
h6vP0c79CdhSWFPyGEjS5A==
-----END PRIVATE KEY-----"""
client_email = "xuongbinhgom-bot@xuongbinhgom.iam.gserviceaccount.com"
client_id = "105435887029398471218"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/xuongbinhgom-bot%40xuongbinhgom.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
