FB_PAGE_TOKEN = "EAAbHPY5s4I4BO4lcMP4spMukwjZCmNdt0twbIGVdHAqUY6Q4OYThmtoFbOqx2tCw3yyZB8fKEnbxQbIAiNc7hvvzO4mVZBLnCpIOHvjaRRvpx9DbQjSUSWtPexZC1j812CZCu5DF6OFZB1sHmVSivK8cb9TvxGFmlJMgQKsF0zAsS0zdNZCbenZCaOZBnt2hZCw5zF0HrK"
FB_PAGE_ID = "2076435142631541"
OPENROUTER_API_KEY = "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"
IG_TOKEN = "EAAbHPY5s4I4BO6n6qPLdxZByl1sStZBB8v6Ey6LC6I7q9azF20qbzQJMCfjlOBFIuS0PUwhFGsBjU0j2Fj81VtZA8fEZB2s9Uv1tMZCHP8i32kBXM407P7ZAiceDqGSAxbltWACQFfkRAUDfHtAvNsoz2LuhdEShZChehqJZBRFxboNzaoQYEx3zx6dAL9ob"
IG_ID = "17841475106267575"
CLOUDINARY_CLOUD_NAME = "dmva9wprt"
CLOUDINARY_API_KEY = "911835649691683"
CLOUDINARY_API_SECRET = "yQXXul-QP0-5qNCtTiKZWlG_5fk"
